sudo: required

notifications:
  email: false

language: cpp

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - sudo pip install cpp-coveralls

before_script:
  - coverage=OFF
  - if [ "$CXX" = "g++" ]; then
        export CXX="g++-4.8" CC="gcc-4.8";
        if [ $TRAVIS_OS_NAME = linux ]; then coverage=ON; fi
    fi

script:
  - ./build-and-test.sh

after_success:
  # Push coverage info on coveralls.io
  - if [ "${coverage}" = "ON" ]; then
         coveralls --exclude 3rdparty -E ".*\.cpp" --gcov /usr/bin/gcov-4.8
         --extension cxx --root ../
         --build-root ../devtools_build;
    fi
